name: build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      pwshgallery: ${{ secrets.GALLERY}}

    steps:
      - uses: actions/checkout@v1
      # build
      - run: |
          Write-Host $Env:GITHUB_REF
          $version = $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          $env:GITHUB_REF | Out-File $env:GITHUB_WORKSPACE/githubref.txt -Encoding utf-8
          & $env:GITHUB_WORKSPACE/build.ps1
        shell: pwsh
      # upload
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ConnectSecure.VM.zip"
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
